version: '3.8'

volumes:
  calcom-database-data:

networks:
  calcom-net:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450

services:
  database:
    image: postgres:latest
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5439:5432"
    volumes:
      - calcom-database-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    networks:
      - calcom-net
    expose:
      - 5432

  calcom:
    image: calcom.docker.scarf.sh/calcom/cal.com
    build:
      context: .
      dockerfile: Dockerfile.test
      args:
        NEXT_PUBLIC_WEBAPP_URL: "${NEXT_PUBLIC_WEBAPP_URL}"
        NEXT_PUBLIC_API_V2_URL: "${NEXT_PUBLIC_API_V2_URL}"
        NEXT_PUBLIC_LICENSE_CONSENT: "${NEXT_PUBLIC_LICENSE_CONSENT}"
        CALCOM_TELEMETRY_DISABLED: "${CALCOM_TELEMETRY_DISABLED}"
        NEXTAUTH_SECRET: "${NEXTAUTH_SECRET}"
        CALENDSO_ENCRYPTION_KEY: "${CALENDSO_ENCRYPTION_KEY}"
        DATABASE_URL: "${DATABASE_URL}"
        DATABASE_DIRECT_URL: "${DATABASE_URL}"
    restart: always
    networks:
      - calcom-net
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DATABASE_HOST}/${POSTGRES_DB}"
      DATABASE_DIRECT_URL: "${DATABASE_URL}"
    depends_on:
      - database
##RUN yarn db-deploy
#RUN yarn --cwd packages/prisma seed-app-store
    command: 
      - yarn
      - db-deploy
      - yarn
      - --cwd
      - packages/prisma
      - seed-app-store


  studio:
    image: calcom.docker.scarf.sh/calcom/cal.com
    restart: always
    networks:
      - calcom-net
    ports:
      - "5555:5555"
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DATABASE_HOST}/${POSTGRES_DB}"
      DATABASE_DIRECT_URL: "${DATABASE_URL}"
    depends_on:
      - database
    command:
      - npx
      - prisma
      - studio
