version: '3.8'

volumes:
  calcom-database-data:

networks:
  calcom-net:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450

services:
  database:
    image: postgres:latest
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5439:5432"
    volumes:
      - calcom-database-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    networks:
      - calcom-net
    expose:
      - 5432

